# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20160526_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentimage',
            options={'managed': False, 'ordering': ['page_number']},
        ),
    ]
