# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_transcriptpage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptpage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
