# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_auto_20160618_2243'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transcriptpage',
            index_together=set([('transcript', 'date'), ('volume', 'volume_seq_number'), ('transcript', 'page_number'), ('transcript', 'seq_number')]),
        ),
    ]
