# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20160525_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
