# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20160525_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
