# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20160616_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEvidenceCode',
            fields=[
                ('id', models.AutoField(db_column='NMTListID', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, db_column='NMTNo', null=True)),
                ('suffix', models.CharField(blank=True, db_column='NMTNoText', max_length=25, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblNMTList',
            },
        ),
        migrations.CreateModel(
            name='DocumentEvidencePrefix',
            fields=[
                ('id', models.AutoField(db_column='NMTCodeID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='NMTCode', max_length=5, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblNMTCodes',
            },
        ),
        migrations.CreateModel(
            name='DocumentExhibitCode',
            fields=[
                ('id', models.AutoField(db_column='CasesListID', primary_key=True, serialize=False)),
                ('prosecution_number', models.IntegerField(blank=True, db_column='ProsExhNo', null=True)),
                ('prosecution_suffix', models.CharField(blank=True, db_column='ProsExhNoSuffix', max_length=5, null=True)),
                ('prosecution_doc_book_number', models.IntegerField(blank=True, db_column='ProsDocBkNo', null=True)),
                ('prosecution_doc_book_suffix', models.CharField(blank=True, db_column='ProsDocBkNoSuffix', max_length=5, null=True)),
                ('defense_name_denormalized', models.CharField(blank=True, db_column='DefExhName', max_length=50, null=True)),
                ('defense_number', models.IntegerField(blank=True, db_column='DefExhNo', null=True)),
                ('defense_suffix', models.CharField(blank=True, db_column='DefExhNoSuffix', max_length=5, null=True)),
                ('defense_doc_name_id', models.IntegerField(blank=True, db_column='DefDocNameID', null=True)),
                ('defense_doc_name', models.CharField(blank=True, db_column='DefDocName', max_length=50, null=True)),
                ('defense_doc_number', models.IntegerField(blank=True, db_column='DefDocNo', null=True)),
                ('defense_doc_suffix', models.CharField(blank=True, db_column='DefDocNoSuffix', max_length=5, null=True)),
                ('defense_doc_book_name_id', models.IntegerField(blank=True, db_column='DefDocBkNameID', null=True)),
                ('defense_doc_book_name', models.CharField(blank=True, db_column='DefDocBkName', max_length=50, null=True)),
                ('defense_doc_book_number', models.IntegerField(blank=True, db_column='DefDocBkNo', null=True)),
                ('defense_doc_book_suffix', models.CharField(blank=True, db_column='DefDocBkNoSuffix', max_length=5, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblCasesList',
            },
        ),
        migrations.CreateModel(
            name='DocumentExhibitCodeName',
            fields=[
                ('id', models.AutoField(db_column='DefenseExhNameID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='DefenseExhName', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblDefenseExhNames',
            },
        ),
    ]
