# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_transcriptpage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptpage',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='transcriptpage',
            index_together=set([('volume', 'volume_seq_number'), ('transcript', 'seq_number'), ('transcript', 'page_label')]),
        ),
    ]
